### PR TITLE
Create pl_PL.lang

### PR DESCRIPTION
**Pull request by Gwolfski**
I did the polish translation, problematic as there is no direct translation for pet in this sense. Couldn't think of about three pets, these are marked TODO

### CODE REVIEW

**Comment by capnkirok** [comment]
Hey, I updated the English file, can you run through again, and find the gaps? Thanks so much, and sorry for the trouble.

**Comment by Gwolfski** [comment]
Done!

**Comment by capnkirok** [comment]
So much of this changed that we need a new one already :)

**Comment by Gwolfski** [comment]
ok, I'll see what I can do

**Comment by Gwolfski** [comment]
Yeah I'll have it done by Friday.

**Comment by Gwolfski** [comment]
Apologies, but my old laptop finally gave up, and I am currently too exhasuted to recover the data. I will be able to get the files off it tommorrow, as my friend has a computer that still has Pata connectors on it. Again, I deeply apologise for this.

**Comment by capnkirok** [comment]
No worries! Your help is great, whenever it comes!

**Pull request closed without merging**
