### PR TITLE
Create ja_JP.lang

### PR DESCRIPTION
**Pull request by RyogaK**
Hi. I feel this mod is awesome!

I tried to translate en_US.lang in Japanese.
Could you adopt this if it's fine?

### CODE REVIEW

**Comment by capnkirok** [comment]
Hey, I just updated the EN version (it was way out of date). Can you run through again and see what's missing? Thank you so much for the help!

**Comment by RyogaK** [comment]
@capnkirok Please review again.
This lang file includes sensitive expression about religions and races.
The politically correct and stuff of religions are not quite generally in japan, so I'm sure that almost Japanese won't understand.
I tried to translate that as not to prejudice, and also it will be meaning for Japanese. :+1:

**Comment by RyogaK** [comment]
@capnkirok Please review again.
This lang file includes sensitive expression about religions and races.
The politically correct and stuff of religions are not quite generally in japan, so I'm sure that almost Japanese won't understand. (We, the Japanese will celebrate Christmas just for us even though we are not christian as you know.)
I tried to translate that as not to prejudice, and also it will be meaning for Japanese. :+1: 

```
Time for the 12 Days of Petmas! The fun begins on December 14. To play, simply craft your Holiday Pet
```

translated to

```
Happy Holiday!! 特別なペットたちが使えます！
(Happy Holiday!! Special pets are available!)
```

`Menorah` is translated to `ユダヤの燭台 (Judean 's candle holder)`
`Mishumaa` is translated to `アフリカン・アメリカンの燭台 (African american's candle holder)`
`Politically Correct` is translated to `人種差別はいけない！ (No more Racism!!)`

**Comment by capnkirok** [comment]
Thanks!

**Pull request merged**
